# Generated by Django 5.0.4 on 2024-05-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_remove_post_author_alter_post_title"),
    ]

    operations = [
        migrations.DeleteModel(name="Post",),
    ]
