# Generated by Django 5.0.4 on 2024-05-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_delete_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("author", models.CharField(max_length=200, verbose_name="작성자")),
                ("content", models.TextField(verbose_name="글내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일시"),
                ),
            ],
            options={"verbose_name": "게시글", "verbose_name_plural": "게시글",},
        ),
    ]
